### PR TITLE
PR: Fixes #137. Fix test for peopleStore. Add blur to cursor when outside viewport.

### LINKED ISSUE #137: Cursor dots don't move with two-finger scroll ("Different preset pane sizes between multiuser")
1. user 1 has the default preset pane size (width)
2. user 2 resizes their preset pane.

Now the dots and output no longer match each user's screen.

It's also appears that the ratio output calc that fires on the resize event doesn't fire when you resize or open/close any panes.

I'm using chrome version 43.0.2357.130

### PR DESCRIPTION
**Pull request by juho**

### CODE REVIEW

File: browser/test/unit/peopleStore.js [hunk 1]
```diff
@@ -86,11 +95,25 @@ describe('PeopleStore', function() {
...
+			assert.equal(pl.y, 32)
+			done()
+		}
+
+		ps._mouseMoveHandler.call(ps, { pageX: 64, pageY: 64 })
+	})
+
+	it('does not dispatch on mousemove when not over the canvas', function(done) {
+
+		this.timeout(testTimeout + 500)
```
Comment (kschzt) [inline browser/test/unit/peopleStore.js]: Please don't use timers in tests, they could be wildly unreliable eg. in a heavily loaded server. :)

Maybe instead throw an error if you *do* get a dispatch (would happen immediately, in the same call stack, anyway) and otherwise just exit

File: browser/scripts/peopleStore.js [hunk 2]
```diff
@@ -41,15 +40,18 @@ PeopleStore.prototype.initialize = function() {
 			case 'uiActiveGraphChanged':
 				that.people[uid].activeGraphUid = payload.activeGraphUid
 				that.emit('activeGraphChanged', that.people[uid])
+				that.people[uid].lastSeen = Date.now()
```
Comment (kschzt) [inline browser/scripts/peopleStore.js]: could move these up above the switch so that no matter what is dispatched, lastSeen for that person is updated

**Comment by kschzt** [comment]
lgtm
